### PR TITLE
Add mapping to MSPointer- and MouseEvents

### PR DESCRIPTION
**Pull request by roele**
transform does not seem to work properly, anyways others work fine according to some sloppy tests. to implement transform properly, http://msdn.microsoft.com/en-us/library/ie/dn433243(v=vs.85).aspx might come in handy. was not able to test it more reliably due to lack of a proper device.

### CODE REVIEW

**Comment by visiongeist** [comment]
thanks:) but I wonder why you added mousedown, mousemove, mouseup handler?

**Comment by roele** [comment]
was meant for having a fallback for mouse based devices. anyways i think it would be probably better to make that functionality pluggable.

**Comment by visiongeist** [comment]
this would break backward compatibility. Because with this assigned handlers are executed also in desktop environments

**Comment by roele** [comment]
good point. removed MouseEvents and added IE11 pointer support.

**Pull request merged**
