### PR TITLE
I've added the compatibility of the desktop browser for toe.js

### PR DESCRIPTION
**Pull request by furybean**
Add the compatibility of the desktop browser, now you can test toe.js in a
desktop browser.

You can only merge src/toe.js，the demo/demo.html change is unnecessary.

### CODE REVIEW

**Comment by visiongeist** [comment]
Hi furybean, thanks for contribution though I'm not convinced if this is really needed. Because:
1. There are no multiple pointers for translate (except if there would be MSPointer support)
2. taphold/swipe doesn't make too much sense on desktop
3. for tap I would ratter go for a alias addon from click

**Comment by furybean** [comment]
Hi, The goal is just for developer test their app in desktop browser conveniencely.

**Comment by visiongeist** [comment]
Chrome supports that with emulated touchevents. Same for iOS simulator. 
If this is just for testing then it should be handled through a build option or an addon

**Comment by furybean** [comment]
OK，I don't know chrome supports emulated touchevents.
I think this is not really needed too. ;-)
Thanks

**Pull request closed without merging**
